modes:
  uhc:
    death-watcher: true
    border-size: 750
    border-x: 0
    border-y: 0
    border-z: 0
    team-damage: false
    team-push: true
    tab-health: true
    below-name-health: true
    achievement-notification: false
  timebomb:
    enabled: true
    countdown-before-explosion: 20
    explosion-power: 5
  cutclean:
    enabled: true
  luckyleaves:
    enabled: true
    golden_apple_chance: 0.01
  noclean:
    enabled: true
    timeout: 5
settings:
  cleanup-world: false